# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e7ad7394b74f8a38454a213505c1a89da868e607673bc82d885db47f3d593c41200ee305e49c11fe1f1a79bb7eabe300fcff3875afaf41f4811afb30cb887a9

test:
  secret_key_base: b4c965ea0d77451070aca30958ff26aeaabeabd600331cc617e673d29380e09cb5ffdb718990fa638d2ab0faba568220e2513ab8892c630c392c05b06ad8e136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
